def helloC():
    print("This is a line")
    print("This is a line")
    print("This is a line")
    print("This is a line")
    print("This is a line")
    print("This is a line")
    print("This is a line")
    print("This is a line")
    print("This is a line")
